package UI;

public class login extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public login() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        userTextField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        loginButtonL = new javax.swing.JButton();
        exitButtonL = new javax.swing.JButton();
        adviceLabelL = new javax.swing.JLabel();
        passTextField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usernameLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        usernameLabel.setText("USUARIO");
        getContentPane().add(usernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 60, 20));

        passwordLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        passwordLabel.setText("CONTRASEÑA");
        getContentPane().add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, 20));

        userTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTextFieldActionPerformed(evt);
            }
        });
        userTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                userTextFieldKeyReleased(evt);
            }
        });
        getContentPane().add(userTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 190, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 320, 10));

        loginButtonL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        loginButtonL.setText("Entrar");
        loginButtonL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonLActionPerformed(evt);
            }
        });
        loginButtonL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                loginButtonLKeyReleased(evt);
            }
        });
        getContentPane().add(loginButtonL, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 90, 40));

        exitButtonL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        exitButtonL.setText("Salir");
        exitButtonL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonLActionPerformed(evt);
            }
        });
        getContentPane().add(exitButtonL, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 90, 40));
        getContentPane().add(adviceLabelL, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 190, 20));

        passTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passTextFieldActionPerformed(evt);
            }
        });
        passTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passTextFieldKeyReleased(evt);
            }
        });
        getContentPane().add(passTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 190, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logoVertiente.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 110, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTextFieldActionPerformed

    private void exitButtonLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonLActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonLActionPerformed

    private void loginButtonLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonLActionPerformed
        if(textFieldIsEmpty()){
           setAdviceLabel("Ingrese datos para el acceso");
        }
        else{
            if(!userAccess()){
                setAdviceLabel("Usuario/Contraseña incorrecta");
            }
            else{
                setAdviceLabel("Acceso permitido");
                dispose();
                functions functionsView = new functions(userTextField.getText());
                userTextField.setText("");
                passTextField.setText("");
                functionsView.setVisible(true);
            }
        }
        
    }//GEN-LAST:event_loginButtonLActionPerformed

    private void passTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passTextFieldActionPerformed

    private void loginButtonLKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loginButtonLKeyReleased
        
    }//GEN-LAST:event_loginButtonLKeyReleased

    private void userTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userTextFieldKeyReleased
        
    }//GEN-LAST:event_userTextFieldKeyReleased

    private void passTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passTextFieldKeyReleased
        
    }//GEN-LAST:event_passTextFieldKeyReleased
    
    private boolean textFieldIsEmpty(){
        return usernameIsEmpty()&& passwordIsEmpty();
    }
    
    private boolean usernameIsEmpty(){
        return userTextField.getText().trim().isEmpty();
    }
    private boolean passwordIsEmpty(){
        return userTextField.getText().trim().isEmpty();
    }
    
    private boolean userAccess(){
        String username = userTextField.getText().trim();
        String password = passTextField.getText();
        return username.equals("admin") && password.equals("1234");
    }
    
    private void setAdviceLabel(String message){
        adviceLabelL.setText(message);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adviceLabelL;
    private javax.swing.JButton exitButtonL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton loginButtonL;
    private javax.swing.JPasswordField passTextField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField userTextField;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
